import {
  Github,
  Linkedin,
  Twitter,
  Instagram,
  Mail,
  FileText,
  ArrowRight,
  ExternalLink,
  Code2,
  Server,
  Database,
  CalendarCheck,
  Cloud,
  Cpu,
  Layers,
  Shield,
  TerminalSquare,
  Puzzle,
  Coffee,
  Fish,
  Plane,
  Music,
  Wand2,
  Amphora,
  BookOpen,
  Target,
  Trophy,
  Users,
  Compass,
  BrainCircuit,
  Sparkles,
  type LucideIcon,
} from 'lucide-react'
import type { IconName } from '@/types'

// lucide-react has no Stack Overflow glyph; reuse a close stand-in.
const iconMap: Record<IconName, LucideIcon> = {
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  'stack-overflow': Compass,
  instagram: Instagram,
  mail: Mail,
  'file-text': FileText,
  'arrow-right': ArrowRight,
  'external-link': ExternalLink,
  code: Code2,
  server: Server,
  database: Database,
  'calendar-check': CalendarCheck,
  cloud: Cloud,
  cpu: Cpu,
  layers: Layers,
  shield: Shield,
  terminal: TerminalSquare,
  puzzle: Puzzle,
  coffee: Coffee,
  fish: Fish,
  plane: Plane,
  music: Music,
  wand: Wand2,
  amphora: Amphora,
  'book-open': BookOpen,
  target: Target,
  trophy: Trophy,
  users: Users,
  compass: Compass,
  brain: BrainCircuit,
  sparkles: Sparkles,
}

export function getIcon(name: IconName): LucideIcon {
  return iconMap[name]
}
